INSERT INTO Characters VALUES (1, 'Borin Thunderfoot', 'A 5th-level Dwarf Fighter, skilled in battle and known for his bravery.', 10, 1);
INSERT INTO Characters VALUES (2, 'Elara Moonshadow', 'A 3rd-level Elf Rogue with a talent for stealth and subterfuge.', 2, 2);
INSERT INTO Characters VALUES (3, 'Fennian Brightstone', 'A 4th-level Halfling Bard, known for his charming performances and quick wit.', 3, 3);
INSERT INTO Characters VALUES (4, 'Xandril the Wise', 'A 6th-level human Wizard, revered for his vast knowledge of arcane arts.', 10, 4);
INSERT INTO Characters VALUES (5, 'Grimnar Stonehand', 'A 2nd-level Gnome Barbarian with a fiery temper and a love for combat.', 7, 5);
INSERT INTO Characters VALUES (6, 'Sylas Greymane', 'A 5th-level Human Paladin, sworn to protect the innocent and wielding divine power.', 10, 6);
INSERT INTO Characters VALUES (7, 'Alyndra Shadowbriar', 'A 7th-level Tiefling Warlock, drawing power from a pact with an otherworldly being.', 3, 7);
INSERT INTO Characters VALUES (8, 'Kara Dawnsinger', 'A 3rd-level Half-Elf Cleric devoted to healing and supporting her allies.', 2, 8);
INSERT INTO Characters VALUES (9, 'Drogar Ironjaw', 'A 2nd-level Dragonborn Fighter with a fierce loyalty to his comrades in arms.', 4, 9);
INSERT INTO Characters VALUES (10, 'Mira Starforge', 'A 4th-level Dwarf Ranger, skilled in tracking and survival skills in the wild.', 5, 10);
INSERT INTO Characters VALUES (11, 'Tharok Fireblade', 'A level 5 Half-Orc Barbarian known for his ferocity in battle.', 5, 11);
INSERT INTO Characters VALUES (12, 'Elara Shadowmoon', 'A level 4 Elf Rogue with unmatched skills in stealth and deception.', 10, 12);
INSERT INTO Characters VALUES (13, 'Brom Earthwalker', 'A level 6 Dwarf Fighter famed for his unyielding defense.', 8, 13);
INSERT INTO Characters VALUES (14, 'Lirael Windwhisper', 'A level 3 Human Sorcerer with a mysterious connection to elemental magic.', 4, 14);
INSERT INTO Characters VALUES (15, 'Gregor Ironfist', 'A level 7 Gnome Cleric who is devoted to healing and support.', 9, 15);
INSERT INTO Characters VALUES (16, 'Sera Brightwater', 'A level 5 Tiefling Bard, captivating audiences with her songs.', 8, 16);
INSERT INTO Characters VALUES (17, 'Fendal Lightfoot', 'A level 2 Halfling Monk with agility and keen insight.', 1, 17);
INSERT INTO Characters VALUES (18, 'Vorrath Bloodthorn', 'A level 8 Dragonborn Paladin, sworn to uphold justice.', 10, 18);
INSERT INTO Characters VALUES (19, 'Mariselle Duskwhisper', 'A level 6 Half-Elf Warlock with dark powers and connections.', 3, 19);
INSERT INTO Characters VALUES (20, 'Korak Stonebreaker', 'A level 1 Half-Orc Bard, brimming with potential and passion.', 6, 20);
INSERT INTO Characters VALUES (21, 'Thalindra', 'Level 5 Elven Sorcerer, skilled in elemental magic.', 2, 21);
INSERT INTO Characters VALUES (22, 'Brugnar', 'Level 4 Dwarf Barbarian, tough as nails and always ready to fight.', 4, 22);
INSERT INTO Characters VALUES (23, 'Mirael', 'Level 3 Human Rogue with a knack for stealth and cunning.', 4, 23);
INSERT INTO Characters VALUES (24, 'Gromok', 'Level 6 Half-Orc Fighter, a brash warrior with fierce combat skills.', 3, 24);
INSERT INTO Characters VALUES (25, 'Lirael', 'Level 5 Tiefling Bard, captivating audiences with enchanting melodies.', 4, 25);
INSERT INTO Characters VALUES (26, 'Dorin', 'Level 2 Halfling Cleric, devoted to healing and support.', 6, 26);
INSERT INTO Characters VALUES (27, 'Faelar', 'Level 8 Wood Elf Ranger, a master tracker and archer.', 6, 27);
INSERT INTO Characters VALUES (28, 'Vespera', 'Level 3 Gnome Wizard, curious and intelligent with a love for knowledge.', 7, 28);
INSERT INTO Characters VALUES (29, 'Ragnor', 'Level 7 Dragonborn Paladin, a beacon of righteousness in battle.', 6, 29);
INSERT INTO Characters VALUES (30, 'Selene', 'Level 4 Aasimar Warlock, channeling dark powers to achieve her goals.', 10, 30);
