INSERT INTO Spells VALUES (1, 'Flame Lash', 2, 'A whip made of flames lashes out at a target, dealing fire damage and igniting them for further burns.', 3, NULL, 'action', '30ft', 'V, S');
INSERT INTO Spells VALUES (2, 'Spectral Shield', 1, 'A shimmering barrier appears, granting bonus armor class against the next attack.', 1, 31, 'reaction with trigger', 'self', 'V, S');
INSERT INTO Spells VALUES (3, 'Whispers of the Mind', 3, 'You invade the mind of a target, forcing them to make a wisdom saving throw or be incapacitated for the duration.', 4, NULL, 'action', '60ft', 'V, S, M (a feather)');
INSERT INTO Spells VALUES (4, 'Mend Wounds', 0, 'Heals a small amount of damage to a target, knitting their wounds with magical energy.', 1, 32, 'action', 'touch', 'V, S');
INSERT INTO Spells VALUES (5, 'Thunderous Step', 2, 'You teleport up to 30ft and leave a thunderous explosion at your original location, dealing damage to nearby enemies.', 0, NULL, 'bonus action', 'self', 'V');
INSERT INTO Spells VALUES (6, 'Barkskin', 3, 'Toughen your skin like bark, increasing your armor class and enhancing your resistances.', 10, 33, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (7, 'Frostbite Aura', 4, 'Create an icy aura that chills enemies within a 10ft radius, slowing their movement and causing frost damage.', 6, NULL, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (8, 'Aura of Clarity', 3, 'Surround yourself with an aura that sharpens the minds of allies, granting bonuses to intelligence checks and saving throws.', 5, 34, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (9, 'Shadow Veil', 2, 'You cloak yourself in shadows, becoming harder to detect and granting a bonus to stealth checks.', 4, 35, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (10, 'Empowered Strike', 5, 'Channel extra magical energy into your weapon attack, dealing additional force damage and pushing the target back.', 0, NULL, 'bonus action', 'self', 'V, S');
INSERT INTO Spells VALUES (11, 'Shadow Veil', 2, 'Surround yourself in a veil of shadows, granting advantage on Dexterity (Stealth) checks and making you harder to detect.', 6, 36, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (12, 'Arcane Shield', 3, 'Create a shimmering barrier of arcane energy that absorbs a number of hit points of damage.', 8, NULL, 'action', 'self', 'V, S, M (a crystal worth at least 50 gold pieces)');
INSERT INTO Spells VALUES (13, 'Frostbite Touch', 0, 'Your touch chills a target, potentially reducing their speed and dealing cold damage.', 1, NULL, 'action', 'touch', 'V, S');
INSERT INTO Spells VALUES (14, 'Guardian Spirit', 4, 'Summon a guardian spirit that provides assistance in battle, granting nearby allies a bonus to attack rolls.', 10, 37, 'action', '30ft', 'V, S, M (a small silver statue of a creature)');
INSERT INTO Spells VALUES (15, 'Illusory Doubles', 3, 'Create illusory duplicates of yourself that confuse enemies, potentially causing attacks to miss.', 5, NULL, 'bonus action', 'self', 'V, S');
INSERT INTO Spells VALUES (16, 'Nature''s Bounty', 1, 'Bless an area, allowing plants to grow and providing food and shelter for allies and creatures nearby.', 4, NULL, '1 minute', 'touch', 'V, S, M (a seed from a plant)');
INSERT INTO Spells VALUES (17, 'Mana Surge', 5, 'Boost your spellcasting ability, allowing you to cast one additional spell this turn at half the normal cost.', 1, NULL, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (18, 'Thunderous Roar', 2, 'Unleash a powerful roar that stuns enemies within a radius, making them vulnerable to the next attack.', 2, NULL, 'action', '30ft', 'V, S');
INSERT INTO Spells VALUES (19, 'Fortify Resolve', 4, 'Temporarily increase an ally''s wisdom and constitution, granting them resilience against mental and physical effects.', 6, 38, 'action', '60ft', 'V, S, M (a drop of sweat from the target)');
INSERT INTO Spells VALUES (20, 'Mystic Flame', 1, 'Conjure a small flame that deals fire damage to a single target.', 1, NULL, 'action', '60ft', 'V, S');
INSERT INTO Spells VALUES (21, 'Shield of Shadows', 2, 'Cloak yourself in shadows, providing bonus to your armor class until your next turn.', 1, 39, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (22, 'Guardian Beast', 3, 'Summon a spectral beast to fight alongside you for the duration of the spell.', 3, NULL, 'action', 'self', 'V, S, M (a drop of blood from a beast)');
INSERT INTO Spells VALUES (23, 'Frostbite Grasp', 2, 'Your hand becomes a frozen weapon, dealing cold damage and reducing target''s movement speed.', 1, NULL, 'bonus action', 'touch', 'V, S');
INSERT INTO Spells VALUES (24, 'Echo of the Ancients', 4, 'Invoke the wisdom of ancient spirits, granting advantage on your next insight and investigation rolls.', 2, NULL, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (25, 'Quicksilver Reflexes', 3, 'Enhance your agility, providing a temporary boost to your dexterity.', 3, 40, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (26, 'Shroud of Mist', 2, 'Surround yourself with a thick mist that obscures vision, granting you advantage on stealth checks.', 2, NULL, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (27, 'Vital Surge', 5, 'Channel divine energy into another creature, healing them for a substantial amount.', 1, NULL, 'action', '30ft', 'V, S, M (a small vial of holy water)');
INSERT INTO Spells VALUES (28, 'Nether Grip', 4, 'Bind a target in shadowy tendrils, preventing their movement and dealing necrotic damage.', 2, NULL, 'action', '30ft', 'V, S');
INSERT INTO Spells VALUES (29, 'Celestial Guard', 6, 'Summon a celestial being to provide guidance and protection for a number of turns.', 5, NULL, 'action', 'self', 'V, S, M (a feather from a celestial)');
INSERT INTO Spells VALUES (30, 'Arcane Armor', 2, 'Surround yourself with a shimmering barrier of arcane energy that increases your armor class.', 10, 41, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (31, 'Frostbite', 0, 'A frigid blast of energy numbs a creature''s body, making it harder for them to act.', 1, NULL, 'action', '60ft', 'V, S');
INSERT INTO Spells VALUES (32, 'Spectral Blade', 3, 'Conjure a blade of psychic energy that you can control and send to strike your enemies at will.', 5, NULL, 'bonus action', '30ft', 'V, S');
INSERT INTO Spells VALUES (33, 'Illusory Duplicates', 4, 'Create illusory duplicates of yourself to confuse enemies and better evade attacks.', 8, NULL, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (34, 'Mind Blast', 5, 'Unleash a wave of psychic energy that damages and incapacitates nearby foes.', 1, NULL, 'action', '20ft', 'V, S, M');
INSERT INTO Spells VALUES (35, 'Harmony of Spirits', 6, 'Create a harmonic aura that strengthens allies, boosting their combat capabilities.', 8, 42, 'action', '30ft', 'V, S');
INSERT INTO Spells VALUES (36, 'Shadow Step', 3, 'Step into the shadows and reappear in another location, allowing for quick evasion or surprise attacks.', 1, NULL, 'bonus action', 'self', 'V, S');
INSERT INTO Spells VALUES (37, 'Fury of the Elements', 7, 'Summon a storm of elemental fury at a targeted area, dealing damage based on the chosen element.', 1, NULL, 'action', '60ft', 'V, S, M');
INSERT INTO Spells VALUES (38, 'Banishment', 4, 'Temporary exile a creature to a harmless demiplane, preventing them from participating in the current encounter.', 1, NULL, 'action', '60ft', 'V, S');
INSERT INTO Spells VALUES (39, 'Celestial Companion', 5, 'Call forth a celestial creature to aid you in battle, fighting alongside you for the duration of the spell.', 10, NULL, 'action', 'self', 'V, S, M');
INSERT INTO Spells VALUES (40, 'Frostfire Bolt', 3, 'Launch a bolt of combined ice and fire at a target, dealing both cold and fire damage.', 1, NULL, 'action', '120ft', 'V, S, M (a small shard of ice and a flame)');
INSERT INTO Spells VALUES (41, 'Whispers of the Void', 4, 'Unleash a haunting whisper that confuses and frightens a creature within range.', 2, NULL, 'action', '90ft', 'V');
INSERT INTO Spells VALUES (42, 'Guardian Spirit', 6, 'Summon a protective spirit that grants temporary hit points and boosts morale to allies within range.', 3, 43, 'action', '30ft', 'V, S, M (a small token from a protective creature)');
INSERT INTO Spells VALUES (43, 'Wings of the Phoenix', 5, 'Transform into a fiery phoenix, granting flight and dealing fire damage to nearby enemies.', 4, NULL, 'action', 'self', 'V, S');
INSERT INTO Spells VALUES (44, 'Stone Skin', 4, 'Protects the target, granting resistance to non-magical bludgeoning, piercing, and slashing damage.', 6, NULL, 'action', 'touch', 'V, S, M (a knob of clay)');
INSERT INTO Spells VALUES (45, 'Arcane Shield', 2, 'A shimmering shield of magic appears, raising the caster''s armor class temporarily.', 3, 44, 'reaction when hit', 'self', 'V, S');
INSERT INTO Spells VALUES (46, 'Summon Elemental', 5, 'Summon an elemental of your choice to fight alongside you for the duration.', 5, NULL, 'action', '90ft', 'V, S, M (a pinch of elemental material)');
INSERT INTO Spells VALUES (47, 'Fade Into Shadows', 2, 'You cloak yourself in shadows, becoming invisible until your next turn or until you attack.', 1, NULL, 'bonus action', 'self', 'V, S');
INSERT INTO Spells VALUES (48, 'Time Dilation', 6, 'Slow down time in a small area, causing all creatures to act more slowly.', 4, NULL, 'action', '30ft', 'V, S');
INSERT INTO Spells VALUES (49, 'Teleportation Circle', 5, 'Create a circle that allows for instant travel to a location you know.', 0, NULL, '10 minutes', 'self', 'V, S, M (a piece of the destination)');
