INSERT INTO Items VALUES (1, 'Frostfire Blade', 'A sword that flickers with icy blue flames. Deals fire and cold damage.', 19);
INSERT INTO Items VALUES (2, 'Ring of Shadows', 'A dark silver ring that grants the wearer greater stealth capabilities.', 20);
INSERT INTO Items VALUES (3, 'Cloak of the Phoenix', 'A vibrant cloak that allows the wearer to burst into flames upon death, dealing fire damage to nearby enemies.', 21);
INSERT INTO Items VALUES (4, 'Amulet of Wisdom', 'A golden amulet adorned with a sapphire, enhancing the wearer''s wisdom and knowledge.', 22);
INSERT INTO Items VALUES (5, 'Boots of the Cat', 'These soft, light boots grant incredible agility and reaction time.', 23);
INSERT INTO Items VALUES (6, 'Shield of Resilience', 'A sturdy shield that grants extra protection against attacks.', 24);
INSERT INTO Items VALUES (7, 'Potion of Elemental Resistance', 'A shimmering potion that grants resistance to one type of elemental damage.', NULL);
INSERT INTO Items VALUES (8, 'Staff of Healing', 'A long wooden staff that aids in the healing of allies.', 25);
INSERT INTO Items VALUES (9, 'Gloves of Thievery', 'These enchanted gloves enhance your skills in deception and stealth.', 26);
INSERT INTO Items VALUES (10, 'Tome of Forgotten Lore', 'An ancient tome filled with lost knowledge that grants insight into the arcane.', 27);
INSERT INTO Items VALUES (11, 'Vortex Ring', 'A shimmering ring that appears to swirl with the colors of the stormy sky.', 28);
INSERT INTO Items VALUES (12, 'Shadow Cloak', 'A cloak woven from the shadows of the night, granting its wearer added stealth.', 29);
INSERT INTO Items VALUES (13, 'Mystic Lens', 'A glass lens that magnifies the essence of magic around you.', 30);
INSERT INTO Items VALUES (14, 'Stonebreaker Gauntlets', 'Heavy gauntlets engraved with ancient runes, designed to crush through rock and stone.', 31);
INSERT INTO Items VALUES (15, 'Amulet of Healing', 'An amulet pulsating with an inner light that seems to soothe pain.', 32);
INSERT INTO Items VALUES (16, 'Boots of the Nightwalker', 'Boots that allow you to move silently and swiftly through darkness.', 33);
INSERT INTO Items VALUES (17, 'Crown of Wisdom', 'A beautifully crafted crown that radiates wisdom, enhancing your mental prowess.', 34);
INSERT INTO Items VALUES (18, 'Phoenix Feather Quill', 'A quill made from the feathers of a phoenix, infused with magic.', 35);
INSERT INTO Items VALUES (19, 'Orb of Elemental Fury', 'A small orb that crackles with elemental energy, capable of unleashing devastating spells.', 36);
INSERT INTO Items VALUES (20, 'Giant''s Belt', 'A thick, heavy belt made from giant hide, increasing the wearer''s strength.', 37);
INSERT INTO Items VALUES (21, 'Amulet of the Mind''s Eye', 'This shimmering amulet enhances the wearer''s mental acuity, allowing clearer insights into the arcane.', 38);
INSERT INTO Items VALUES (22, 'Gloves of Sneaky Shadows', 'These dark leather gloves seem to absorb light, granting an advantage to stealthy maneuvers.', 39);
INSERT INTO Items VALUES (23, 'Longsword of the Storm', 'This elegantly crafted longsword crackles with lightning energy, ready to unleash a storm upon foes.', 40);
INSERT INTO Items VALUES (24, 'Cloak of the Fey', 'A stunning cloak adorned with ethereal patterns that shift, providing camouflage in natural settings.', 41);
INSERT INTO Items VALUES (25, 'Belt of Giant''s Strength', 'This thick leather belt greatly enhances the bearer''s physical power.', 42);
INSERT INTO Items VALUES (26, 'Ring of Eternal Flame', 'This ring burns perpetually with magical fire, warming the wearer and illuminating dark places.', 43);
INSERT INTO Items VALUES (27, 'Boots of Endless Whispers', 'These soft boots allow for silent movement and the ability to hear whispers from afar.', 44);
INSERT INTO Items VALUES (28, 'Quiver of Recall', 'A magical quiver that allows for the retrieval of any arrow shot from it, returning to the quiver after use.', 45);
INSERT INTO Items VALUES (29, 'Staff of Illusions', 'A beautifully carved staff that allows the caster to weave illusions with a flick of the wrist.', 46);
INSERT INTO Items VALUES (30, 'Potion of Resilience', 'A shimmering liquid within a glass vial that enhances the drinker''s stamina temporarily.', NULL);
INSERT INTO Items VALUES (31, 'Celestial Compass', 'An enchanted compass that always points toward the nearest celestial alignment.', 47);
INSERT INTO Items VALUES (32, 'Frostfire Blade', 'A glowing sword that emits both frost and fire. Its power is beyond that of normal weapons.', 48);
INSERT INTO Items VALUES (33, 'Potion of Mind''s Eye', 'A shimmering liquid that enhances your mental clarity and focus.', 49);
INSERT INTO Items VALUES (34, 'Ring of Shadows', 'A ring that grants the wearer the power to meld into shadows, becoming nearly invisible in dim light.', 50);
INSERT INTO Items VALUES (35, 'Cloak of the Wind', 'A lightweight cloak that ripples like the wind, granting its wearer enhanced agility.', 51);
INSERT INTO Items VALUES (36, 'Bracers of the Cunning Fox', 'These bracers are said to be imbued with the spirit of a cunning fox, enhancing quick thinking.', 52);
INSERT INTO Items VALUES (37, 'Amulet of Vitality', 'An amulet promoting health and vitality; it''s said to ward off disease.', 53);
INSERT INTO Items VALUES (38, 'Enchanted Quiver', 'A quiver that magically replenishes arrows at dawn each day.', NULL);
INSERT INTO Items VALUES (39, 'Scepter of the Mind', 'A powerful scepter that enhances its user''s mental capabilities in combat.', 54);
INSERT INTO Items VALUES (40, 'Boots of Elven Grace', 'Lightweight boots that allow for graceful and agile movements.', 55);
INSERT INTO Items VALUES (41, 'Shadow Cloak', 'A dark cloak that ripples like shadow, granting the wearer enhanced stealth capabilities.', 56);
INSERT INTO Items VALUES (42, 'Flame Tongue Sword', 'A sword that ignites in flames when drawn, dealing additional fire damage.', 57);
INSERT INTO Items VALUES (43, 'Ring of Invisibility', 'A shimmering ring that grants the ability to turn invisible.', 58);
INSERT INTO Items VALUES (44, 'Giant''s Gauntlet', 'A massive gauntlet that enhances the wearer''s strength.', 59);
INSERT INTO Items VALUES (45, 'Potion of Greater Healing', 'A red potion that restores a greater amount of health when consumed.', NULL);
INSERT INTO Items VALUES (46, 'Amulet of Protection', 'An amulet that provides a mystical barrier to shield the wearer.', 60);
INSERT INTO Items VALUES (47, 'Tome of Arcane Knowledge', 'A dusty tome filled with ancient spells and rituals.', 61);
INSERT INTO Items VALUES (48, 'Boots of Speed', 'These enchanted boots allow the wearer to move at incredible speeds.', 62);
INSERT INTO Items VALUES (49, 'Wand of Magic Missile', 'A slender wand that automatically conjures magical missiles.', 63);
INSERT INTO Items VALUES (50, 'Cursed Necklace', 'An alluring necklace that whispers dark secrets but drains the wearer''s vitality.', 64);
